# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RaceTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_trait_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='race_traits',
            field=models.ManyToManyField(to='cof.RaceTrait'),
        ),
        migrations.AddField(
            model_name='perso',
            name='profiles',
            field=models.ManyToManyField(to='cof.Profile'),
        ),
        migrations.AddField(
            model_name='perso',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Race'),
        ),
    ]
