# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0003_auto_20160624_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='spell',
            field=models.BooleanField(default=False),
        ),
    ]
