# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0004_auto_20160624_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicway',
            name='way_description',
        ),
        migrations.AddField(
            model_name='basicway',
            name='way_capacity',
            field=models.TextField(blank=True),
        ),
    ]
