# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0005_auto_20160624_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='magic_modifier',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
