# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0006_profile_magic_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='slug',
            field=models.SlugField(default='Burrin-Buveur-de-Biere-1', max_length=105),
            preserve_default=False,
        ),
    ]
