# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0007_perso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='slug',
            field=models.SlugField(max_length=105, unique=True),
        ),
    ]
