# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0008_auto_20160625_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family',
            field=models.CharField(choices=[('VOY', 'Voyageur'), ('COM', 'Combattant'), ('LAN', 'Lanceur de sort'), ('NOF', 'Pas de famille')], default='NOF', max_length=3),
        ),
    ]
