# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0009_profile_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_limitation_name', models.CharField(max_length=30)),
                ('limitation_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='perso',
            name='perso_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_resume',
            field=models.TextField(default='resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sup_charisma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sup_constitution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sup_dexterity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sup_intelligence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sup_strength',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sup_wisdom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='prejudice',
            field=models.TextField(default='prejudice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='race_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_traits',
            field=models.ManyToManyField(blank=True, to='cof.RaceTrait'),
        ),
        migrations.AddField(
            model_name='race',
            name='race_limitations',
            field=models.ManyToManyField(blank=True, to='cof.RaceLimitation'),
        ),
    ]
