# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 08:40
from __future__ import unicode_literals

from django.db import migrations

def gen_slug_race(apps, shema_editor):
    Race = apps.get_model('cof', 'Race')
    for row in Race.objects.all():
        row.slug = '%s-%s' % (row.race_name, row.id)
        row.save()

def gen_slug_profile(apps, shema_editor):
    Profile = apps.get_model('cof', 'Profile')
    for row in Profile.objects.all():
        row.slug = '%s-%s' % (row.profile_name, row.id)
        row.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0012_auto_20160627_1040'),
    ]

    operations = [ 
            migrations.RunPython(gen_slug_race, reverse_code=migrations.RunPython.noop),
            migrations.RunPython(gen_slug_profile, reverse_code=migrations.RunPython.noop),
    ]
