# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0017_auto_20160627_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='perso_picture',
            field=models.ImageField(blank=True, upload_to='images/persos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profiles'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_picture',
            field=models.ImageField(blank=True, upload_to='images/races'),
        ),
    ]
