# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0018_auto_20160627_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sup_dexterity',
            field=models.BooleanField(default=False, verbose_name='FOR'),
        ),
    ]
