# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0019_auto_20160627_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacialWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racial_way_name', models.CharField(max_length=30)),
                ('rank_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_five', to='cof.Rank')),
                ('rank_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_four', to='cof.Rank')),
                ('rank_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_one', to='cof.Rank')),
                ('rank_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_three', to='cof.Rank')),
                ('rank_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_two', to='cof.Rank')),
            ],
        ),
    ]
