# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0021_race_racial_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicway',
            name='ranks',
        ),
        migrations.AddField(
            model_name='basicway',
            name='rank_five',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_rank_five', to='cof.Rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicway',
            name='rank_four',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_rank_four', to='cof.Rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicway',
            name='rank_one',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_rank_one', to='cof.Rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicway',
            name='rank_three',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_rank_three', to='cof.Rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicway',
            name='rank_two',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_rank_two', to='cof.Rank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racialway',
            name='rank_five',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_rank_five', to='cof.Rank'),
        ),
        migrations.AlterField(
            model_name='racialway',
            name='rank_four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_rank_four', to='cof.Rank'),
        ),
        migrations.AlterField(
            model_name='racialway',
            name='rank_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_rank_one', to='cof.Rank'),
        ),
        migrations.AlterField(
            model_name='racialway',
            name='rank_three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_rank_three', to='cof.Rank'),
        ),
        migrations.AlterField(
            model_name='racialway',
            name='rank_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_rank_two', to='cof.Rank'),
        ),
    ]
