# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0022_auto_20160628_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='basic_ways',
            field=models.ManyToManyField(to='cof.BasicWay'),
        ),
    ]
