# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0024_auto_20160628_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'Ordinaire'), (2, 'Précieux'), (3, 'Exotique'), (4, 'Rare'), (5, 'Très rare')], default=1)),
                ('quality', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_unit', models.CharField(max_length=30)),
                ('is_magic', models.BooleanField(default=False)),
                ('armor_name', models.CharField(max_length=30)),
                ('armor_def', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArmorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'Ordinaire'), (2, 'Précieux'), (3, 'Exotique'), (4, 'Rare'), (5, 'Très rare')], default=1)),
                ('quality', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_unit', models.CharField(max_length=30)),
                ('is_magic', models.BooleanField(default=False)),
                ('material_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'Ordinaire'), (2, 'Précieux'), (3, 'Exotique'), (4, 'Rare'), (5, 'Très rare')], default=1)),
                ('quality', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quantity_unit', models.CharField(max_length=30)),
                ('is_magic', models.BooleanField(default=False)),
                ('weapon_name', models.CharField(max_length=30)),
                ('weapon_range', models.PositiveSmallIntegerField(default=5)),
                ('nb_dice_damage', models.PositiveSmallIntegerField(default=2)),
                ('dice_side_damage', models.PositiveSmallIntegerField(default=2)),
                ('critical', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.WeaponCategory'),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.ArmorCategory'),
        ),
    ]
