# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0025_auto_20160628_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weapons_armors_capacities',
            field=models.TextField(default='capacity'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='critical',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dice_side_damage',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='nb_dice_damage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
