# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0026_auto_20160701_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='recharching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='recharging_modality',
            field=models.TextField(blank=True, default='recharge'),
        ),
    ]
