# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0028_auto_20160701_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='recharging',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 action simple'), (2, '1 action limitée')]),
        ),
    ]
