# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0030_auto_20160701_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='recharging',
            field=models.CharField(blank=True, choices=[('simple', '1 action simple'), ('limited', '1 action limitée')], max_length=7),
        ),
    ]
