# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0031_auto_20160701_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileArmors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='special_material_start',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_range',
            field=models.PositiveSmallIntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='profileweapons',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Profile'),
        ),
        migrations.AddField(
            model_name='profileweapons',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Weapon'),
        ),
        migrations.AddField(
            model_name='profilematerials',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Profile'),
        ),
        migrations.AddField(
            model_name='profilearmors',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cof.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='armor_start',
            field=models.ManyToManyField(blank=True, through='cof.ProfileArmors', to='cof.Armor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='material_start',
            field=models.ManyToManyField(blank=True, through='cof.ProfileMaterials', to='cof.Material'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weapons_start',
            field=models.ManyToManyField(blank=True, through='cof.ProfileWeapons', to='cof.Weapon'),
        ),
    ]
