# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0032_auto_20160701_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_range',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
